- iceoryx_ros2_bridge/src/typesupport_helpers.hpp
fixes https://github.com/ros2/rmw_iceoryx/issues/1
The typesupport helpers as well as the generic sub/pub are a direct copy of the code available in rosbag2. I thought there was already an open issue for it, but ideally that code should live somewhere in rosidl or rclcpp.
Signed-off-by: Knese Karsten <karsten@openrobotics.org>
> remove rosbag2 dependency

- rmw_iceoryx_cpp/src/internal/iceoryx_topic_names_and_types.cpp
- rmw_iceoryx_cpp/src/rmw_node_names.cpp
- rmw_iceoryx_cpp/src/rmw_take.cpp
iceoryx's latest commits introduced a breaking change to their existing API. This PR reflects these changes in the rmw implementation.
cc @michael-poehnl 
CI:
[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8871)](https://ci.ros2.org/job/ci_linux/8871/)
Signed-off-by: Knese Karsten <karsten.knese@us.bosch.com>
> apply changes for latest iceoryx API

- README.md
- iceoryx_ros2_bridge/src/iceoryx_ros2_bridge.cpp
- rmw_iceoryx_cpp/CMakeLists.txt
- rmw_iceoryx_cpp/include/rmw_iceoryx_cpp/iceoryx_name_conversion.hpp
- rmw_iceoryx_cpp/package.xml
- rmw_iceoryx_cpp/src/internal/iceoryx_name_conversion.cpp
- rmw_iceoryx_cpp/src/internal/iceoryx_topic_names_and_types.cpp
- rmw_iceoryx_cpp/test/iceoryx_name_conversion_test.cpp
To be able to use `iceoryx`s native applications with `ros 2` based applications the package name defined from service and event name must be valid for `ros 2` as package name. Forcing lowercase in the package name only partially fixes this issue. As far as I know there are changes planned regarding types in `iceoryx`, so I would propose this fix, till we can focus on the new type handling.
> force lower case for ros package name

- .github/workflows/iceoryx.yml
- .github/workflows/main.yml
- rmw_iceoryx_cpp/CMakeLists.txt
- rmw_iceoryx_cpp/include/rmw_iceoryx_cpp/iceoryx_deserialize.hpp
- rmw_iceoryx_cpp/include/rmw_iceoryx_cpp/iceoryx_name_conversion.hpp
- rmw_iceoryx_cpp/include/rmw_iceoryx_cpp/iceoryx_topic_names_and_types.hpp
- rmw_iceoryx_cpp/package.xml
- rmw_iceoryx_cpp/src/internal/iceoryx_name_conversion.cpp
- rmw_iceoryx_cpp/src/rmw_publish.cpp
- rmw_iceoryx_cpp/src/rmw_serialize.cpp
- rmw_iceoryx_cpp/src/rmw_take.cpp
- rmw_iceoryx_cpp/test/iceoryx_name_conversion_test.cpp
fixes #13 
this is work in progress. 
* hide internal topics to avoid recording with `ros2 bag record -a`. This change requires https://github.com/ros2/rosbag2/pull/332
* support for `rmw_serialize` as well as `rmw_publish_serialized_message`
* support for `rmw_deserialize` as well as `rmw_take_serialized_message`
> support for rosbags

- .github/workflows/additional_repos.repos
- .github/workflows/main.yml
- rmw_iceoryx_cpp/CMakeLists.txt
- rmw_iceoryx_cpp/src/rmw_event.cpp
- rmw_iceoryx_cpp/src/rmw_get_topic_endpoint_info.cpp
- rmw_iceoryx_cpp/src/rmw_node.cpp
- rmw_iceoryx_cpp/src/rmw_node_names.cpp
> Adding event and topic info functions to RMW

- iceoryx_ros2_bridge/src/generic_publisher.cpp
https://github.com/ros2/rclcpp/pull/1119 introduced an API break. 
Signed-off-by: Knese Karsten <karsten.knese@us.bosch.com>
> publisher handle returns shared pointer

- .github/workflows/main.yml
given that the current rmw_iceoryx_cpp is not working with the latest iceoryx version, I am going to disable the GH actions for this.
@budrus I'll leave it up to you to re-enable them once iceoryx v1.0 is out of the door and work on the rmw is going to be resumed.
> disable cron job for rmw_iceoryx

- .github/workflows/additional_repos.repos
- .github/workflows/main.yml
- README.md
- iceoryx_ros2_bridge/src/generic_subscription.cpp
- iceoryx_ros2_bridge/src/generic_subscription.hpp
- rmw_iceoryx_cpp/CMakeLists.txt
- rmw_iceoryx_cpp/include/rmw_iceoryx_cpp/iceoryx_type_info_introspection.hpp
- rmw_iceoryx_cpp/src/internal/iceoryx_deserialize.cpp
- rmw_iceoryx_cpp/src/internal/iceoryx_serialize.cpp
- rmw_iceoryx_cpp/src/internal/iceoryx_type_info_introspection.cpp
- rmw_iceoryx_cpp/src/rmw_network_flow_endpoint.cpp
- rmw_iceoryx_cpp/src/rmw_node.cpp
- rmw_iceoryx_cpp/src/rmw_publisher.cpp
- rmw_iceoryx_cpp/src/rmw_qos.cpp
* Remove iceoryx repos file as iceoryx is now available in upstream ROS 2
* Adhere to new galactic APIs
* Refactor type support calls and remove code duplication
* Talker/Listener demo
* Basic `ros2` command line support
* `RMW_IMPLEMENTATION=rmw_iceoryx_cpp ros2 topic echo /chatter`
Closes #48
> Update rmw_iceoryx for galactic

- rmw_iceoryx_cpp/src/internal/iceoryx_serialization_common.hpp
\<stdexcept\> is needed by std::runtime_error.  Ref: [std::runtime_error](https://en.cppreference.com/w/cpp/error/runtime_error)
Error 
`Starting >>> rmw_iceoryx_cpp
--- stderr: rmw_iceoryx_cpp                             
In file included from /home/homalozoa/temp/ice_test/src/rmw_iceoryx/rmw_iceoryx_cpp/src/internal/./iceoryx_serialize_typesupport_c.hpp:28,
from /home/homalozoa/temp/ice_test/src/rmw_iceoryx/rmw_iceoryx_cpp/src/internal/iceoryx_serialize.cpp:31:
/home/homalozoa/temp/ice_test/src/rmw_iceoryx/rmw_iceoryx_cpp/src/internal/././iceoryx_serialization_common.hpp: In function ‘std::pair<const char*, unsigned int> rmw_iceoryx_cpp::pop_sequence_size(const char*)’:
/home/homalozoa/temp/ice_test/src/rmw_iceoryx/rmw_iceoryx_cpp/src/internal/././iceoryx_serialization_common.hpp:60:16: …
> Add include header <stdexcept> to fix build error

- README.md
I'm not sure how you do the backporting, but I have targetted master, please tell me if you want this PR to be against the default galactic branch.
> change executable name for RouDi to iox-roudi in README.md

- README.md
Same as #64 , targeting galactic branch.
Signed-off-by: ijnek <kenjibrameld@gmail.com>
> change executable name for RouDi to iox-roudi (galactic target)

- rmw_iceoryx_cpp/src/internal/iceoryx_name_conversion.cpp
- rmw_iceoryx_cpp/src/internal/iceoryx_type_info_introspection.cpp
This PR fixes a bug preventing Python support (#57) by allowing the usage of the C type support.
I confirmed the bugfix by running the following four commands in four separate terminals:
```
iox-roudi -l verbose
RMW_IMPLEMENTATION=rmw_iceoryx_cpp ros2 run demo_nodes_cpp talker
RMW_IMPLEMENTATION=rmw_iceoryx_cpp ros2 run demo_nodes_py listener
RMW_IMPLEMENTATION=rmw_iceoryx_cpp ros2 topic echo /chatter
```
Screenshot of the [iceoryx introspection](https://iceoryx.io/v1.0.1/getting-started/examples/icecrystal/) without fix (pub/sub not connected):
Screenshot of the [iceoryx introspection](https://iceoryx.io/v1.0.1/getting-started/examples/icecrystal/) with fix:
Signed-off-by: Simon Hoinkis <simon.hoinkis@apex.ai>
> Fix Python support by using C type support for message name lookup

- rmw_iceoryx_cpp/src/iceoryx_generate_gid.hpp
- rmw_iceoryx_cpp/src/internal/iceoryx_generate_gid.cpp
- rmw_iceoryx_cpp/src/rmw_compare_guids_equal.cpp
- rmw_iceoryx_cpp/src/rmw_get_gid_for_publisher.cpp
- rmw_iceoryx_cpp/src/types/iceoryx_publisher.hpp
* Use `iox::UniquePortId` from iceoryx
* Implement `rmw_compare_gids_equal()`
Closes #47
Signed-off-by: Simon Hoinkis simon.hoinkis@apex.ai
> Add gid support

- rmw_iceoryx_cpp/src/rmw_qos.cpp
This PR fixes a crash in `rqt_graph` due to unimplemented `rmw_qos_profile_check_compatible`
Closes #68
Signed-off-by: Simon Hoinkis <simon.hoinkis@apex.ai>
> Implement `rmw_qos_profile_check_compatible`

- rmw_iceoryx_cpp/CMakeLists.txt
- rmw_iceoryx_cpp/src/rmw_publisher.cpp
- rmw_iceoryx_cpp/src/rmw_subscription.cpp
* Address build issues on macOS from #82
* Call correct destructor in `Publisher` and `Subscriber`
* Fix dependency of name conversion lib
> Fix macOS build

- rmw_iceoryx_cpp/src/rmw_init.cpp
> Use `rcutils_get_executable_name` to get the name of the process

- .github/workflows/lint.yml
- .github/workflows/main.yml
- README.md
- rmw_iceoryx_cpp/CMakeLists.txt
- rmw_iceoryx_cpp/include/rmw_iceoryx_cpp/iceoryx_deserialize.hpp
- rmw_iceoryx_cpp/include/rmw_iceoryx_cpp/iceoryx_name_conversion.hpp
- rmw_iceoryx_cpp/include/rmw_iceoryx_cpp/iceoryx_serialize.hpp
- rmw_iceoryx_cpp/include/rmw_iceoryx_cpp/iceoryx_topic_names_and_types.hpp
- rmw_iceoryx_cpp/include/rmw_iceoryx_cpp/iceoryx_type_info_introspection.hpp
- rmw_iceoryx_cpp/package.xml
- rmw_iceoryx_cpp/src/internal/iceoryx_deserialize.cpp
- rmw_iceoryx_cpp/src/internal/iceoryx_deserialize_typesupport_c.hpp
- rmw_iceoryx_cpp/src/internal/iceoryx_deserialize_typesupport_cpp.hpp
- rmw_iceoryx_cpp/src/internal/iceoryx_get_topic_endpoint_info.cpp
- rmw_iceoryx_cpp/src/internal/iceoryx_name_conversion.cpp
- rmw_iceoryx_cpp/src/internal/iceoryx_serialize.cpp
- rmw_iceoryx_cpp/src/internal/iceoryx_topic_names_and_types.cpp
- rmw_iceoryx_cpp/src/internal/iceoryx_type_info_introspection.cpp
- rmw_iceoryx_cpp/src/rmw_client.cpp
- rmw_iceoryx_cpp/src/rmw_init.cpp
- rmw_iceoryx_cpp/src/rmw_publisher.cpp
- rmw_iceoryx_cpp/src/rmw_request.cpp
- rmw_iceoryx_cpp/src/rmw_response.cpp
- rmw_iceoryx_cpp/src/rmw_service.cpp
- rmw_iceoryx_cpp/src/rmw_service_names_and_types.cpp
- rmw_iceoryx_cpp/src/rmw_service_server_is_available.cpp
- rmw_iceoryx_cpp/src/rmw_subscription.cpp
- rmw_iceoryx_cpp/src/rmw_wait.cpp
- rmw_iceoryx_cpp/src/types/iceoryx_client.hpp
- rmw_iceoryx_cpp/src/types/iceoryx_server.hpp
Cherry-picked the following PRs:
* https://github.com/ros2/rmw_iceoryx/pull/84 :heavy_check_mark: 
* https://github.com/ros2/rmw_iceoryx/pull/90 :heavy_check_mark: 
* https://github.com/ros2/rmw_iceoryx/pull/97 :heavy_check_mark: 
* https://github.com/ros2/rmw_iceoryx/pull/96 :heavy_check_mark:
> Forward port changes from `humble` to `master` branch

- rmw_iceoryx_cpp/CMakeLists.txt
- rmw_iceoryx_cpp/src/iceoryx_generate_gid.hpp
- rmw_iceoryx_cpp/src/internal/iceoryx_generate_gid.cpp
- rmw_iceoryx_cpp/src/rmw_client.cpp
- rmw_iceoryx_cpp/src/rmw_count.cpp
- rmw_iceoryx_cpp/src/rmw_dynamic_type_support.cpp
- rmw_iceoryx_cpp/src/types/iceoryx_client.hpp
1. [x] Add `rmw_count_clients`
2. [x] Add `rmw_count_services`
Closes #100
> Forward port changes from `iron` to `master` branch + Add new `rmw_count_*` functions 

- rmw_iceoryx_cpp/src/rmw_request.cpp
- rmw_iceoryx_cpp/src/rmw_response.cpp
- rmw_iceoryx_cpp/src/types/iceoryx_server.hpp
> Address known limitation in service/client

- rmw_iceoryx_cpp/CMakeLists.txt
- rmw_iceoryx_cpp/include/rmw_iceoryx_cpp/iceoryx_name_conversion.hpp
- rmw_iceoryx_cpp/src/rmw_init.cpp
- rmw_iceoryx_cpp/src/rmw_node.cpp
- rmw_iceoryx_cpp/src/rmw_publisher.cpp
- rmw_iceoryx_cpp/src/rmw_request.cpp
- rmw_iceoryx_cpp/src/rmw_response.cpp
- rmw_iceoryx_cpp/src/rmw_service.cpp
- rmw_iceoryx_cpp/src/rmw_subscription.cpp
- rmw_iceoryx_cpp/src/types/iceoryx_server.hpp
> Address known limitation in service/client (rolling)
